name: cinarium
description: Cinarium Desktop For Flutter
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  window_manager: any
  clipboard: ^0.1.3
  go_router: ^7.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  lottie: ^2.3.2
  path: ^1.8.2
  flutter_acrylic: ^1.1.0
  dynamic_color: ^1.6.3
  material_color_utilities: ^0.8.0
  provider: ^6.0.5
  system_info2: ^3.0.2
  waterfall_flow: any
  json_annotation: ^4.8.1
  async: any
  freezed_annotation: ^2.2.0
  extended_image: ^8.0.0
  qr_flutter: ^4.1.0
  reorderables: ^0.6.0
  desktop_multi_window: ^0.2.0
  bridge:
    path: ./bridge
  cinarium_core:
    path: rust_builder
  super_context_menu:
    path: ./super_context_menu
  animated_toggle_switch: ^0.8.3
  flutter_svg: ^2.0.10+1
  file_picker: ^8.0.7
  material_symbols_icons: ^4.2788.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.3.3
  json_serializable: ^6.1.4
  freezed: ^2.3.5
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lottie/

flutter_launcher_icons:
  android: false
  ios: false
  web:
    generate: false
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo.png"
