// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class HttpConfig {
  final int port;

  const HttpConfig({
    required this.port,
  });

  @override
  int get hashCode => port.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HttpConfig &&
          runtimeType == other.runtimeType &&
          port == other.port;
}

class TaskConfig {
  final BigInt thread;
  final PathBuf tidyFolder;

  const TaskConfig({
    required this.thread,
    required this.tidyFolder,
  });

  @override
  int get hashCode => thread.hashCode ^ tidyFolder.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskConfig &&
          runtimeType == other.runtimeType &&
          thread == other.thread &&
          tidyFolder == other.tidyFolder;
}
