// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'model/source.dart';
import 'model/video.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UntreatedVideoData>>
abstract class UntreatedVideoData implements RustOpaqueInterface {
  Future<List<UntreatedVideo>> getVideos();

  Future<BigInt> getVideosSize();

  static Future<UntreatedVideoData> newInstance() =>
      RustLib.instance.api.crateFileUntreatedVideoDataNewInstance();

  set textFilter(String text);

  List<Source> get sources;

  String get textFilter;

  Future<String?> unwatchSourceF(
      {required Source source, required bool syncDelete});

  Future<String?> watchSourcePathStringF({required String path});
}
