// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'native/task_api.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class PoolData {
  final PoolStatus status;
  final List<(String, TaskOperationalData)> tasks;

  const PoolData({
    required this.status,
    required this.tasks,
  });

  @override
  int get hashCode => status.hashCode ^ tasks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PoolData &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          tasks == other.tasks;
}

class TaskMetadata {
  final String name;
  final int videoId;

  const TaskMetadata({
    required this.name,
    required this.videoId,
  });

  @override
  int get hashCode => name.hashCode ^ videoId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskMetadata &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          videoId == other.videoId;
}

class TaskOperationalData {
  final TaskStatus status;
  final int schedule;
  final String lastLog;
  final DateTime createAt;
  final TaskMetadata metadata;

  const TaskOperationalData({
    required this.status,
    required this.schedule,
    required this.lastLog,
    required this.createAt,
    required this.metadata,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      schedule.hashCode ^
      lastLog.hashCode ^
      createAt.hashCode ^
      metadata.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskOperationalData &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          schedule == other.schedule &&
          lastLog == other.lastLog &&
          createAt == other.createAt &&
          metadata == other.metadata;
}
