// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../app.dart';
import '../frb_generated.dart';
import '../lib.dart';
import '../native.dart';
import '../task/crawler.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> initAppLog() =>
    RustLib.instance.api.crateNativeSystemApiInitAppLog();

Future<void> runWebApi() =>
    RustLib.instance.api.crateNativeSystemApiRunWebApi();

Future<void> stopWebApi() =>
    RustLib.instance.api.crateNativeSystemApiStopWebApi();

bool getHttpStatus() =>
    RustLib.instance.api.crateNativeSystemApiGetHttpStatus();

String getLocalIp() => RustLib.instance.api.crateNativeSystemApiGetLocalIp();

Future<TaskConfig> getTaskConf() =>
    RustLib.instance.api.crateNativeSystemApiGetTaskConf();

Future<HttpConfig> getHttpConf() =>
    RustLib.instance.api.crateNativeSystemApiGetHttpConf();

Future<void> updateHttpPort({required int port}) =>
    RustLib.instance.api.crateNativeSystemApiUpdateHttpPort(port: port);

Future<void> updateTaskThread({required BigInt thread}) =>
    RustLib.instance.api.crateNativeSystemApiUpdateTaskThread(thread: thread);

Future<void> updateTaskTidyFolder() =>
    RustLib.instance.api.crateNativeSystemApiUpdateTaskTidyFolder();

Future<void> openInExplorer({required String path}) =>
    RustLib.instance.api.crateNativeSystemApiOpenInExplorer(path: path);

Future<void> openInDefaultSoftware({required String path}) =>
    RustLib.instance.api.crateNativeSystemApiOpenInDefaultSoftware(path: path);

Future<void> changeCrawlerTemplatesPriority(
        {required List<(int, int)> prioritys}) =>
    RustLib.instance.api.crateNativeSystemApiChangeCrawlerTemplatesPriority(
        prioritys: prioritys);

Future<void> switchCrawlerTemplateEnabled({required int id}) =>
    RustLib.instance.api
        .crateNativeSystemApiSwitchCrawlerTemplateEnabled(id: id);

List<CrawlerTemplate> getCrawlerTemplates() =>
    RustLib.instance.api.crateNativeSystemApiGetCrawlerTemplates();

String pathBuf2String({required PathBuf path}) =>
    RustLib.instance.api.crateNativeSystemApiPathBuf2String(path: path);

PathBuf string2PathBuf({required String path}) =>
    RustLib.instance.api.crateNativeSystemApiString2PathBuf(path: path);

ListenerHandle listenerHttpStatus(
        {required FutureOr<void> Function(bool) dartCallback}) =>
    RustLib.instance.api
        .crateNativeSystemApiListenerHttpStatus(dartCallback: dartCallback);

ListenerHandle listenerUntreatedFile(
        {required FutureOr<void> Function() dartCallback}) =>
    RustLib.instance.api
        .crateNativeSystemApiListenerUntreatedFile(dartCallback: dartCallback);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Template < VideoDataInterim >>>
abstract class TemplateVideoDataInterim implements RustOpaqueInterface {}
