// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Metadata>>
abstract class Metadata implements RustOpaqueInterface {
  String get extension;

  String get filename;

  String get path;

  BigInt get size;
}

class Attr {
  final int id;
  final String name;

  const Attr({
    required this.id,
    required this.name,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Attr &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}

class HomeVideo {
  final int id;
  final String name;
  final String title;
  final String releaseTime;
  final int duration;
  final double thumbnailRatio;
  final Metadata matedata;

  const HomeVideo({
    required this.id,
    required this.name,
    required this.title,
    required this.releaseTime,
    required this.duration,
    required this.thumbnailRatio,
    required this.matedata,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      title.hashCode ^
      releaseTime.hashCode ^
      duration.hashCode ^
      thumbnailRatio.hashCode ^
      matedata.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HomeVideo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          title == other.title &&
          releaseTime == other.releaseTime &&
          duration == other.duration &&
          thumbnailRatio == other.thumbnailRatio &&
          matedata == other.matedata;
}

class UntreatedVideo {
  final int id;
  final String crawlName;
  final bool isHidden;
  final Metadata metadata;

  const UntreatedVideo({
    required this.id,
    required this.crawlName,
    required this.isHidden,
    required this.metadata,
  });

  @override
  int get hashCode =>
      id.hashCode ^ crawlName.hashCode ^ isHidden.hashCode ^ metadata.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UntreatedVideo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          crawlName == other.crawlName &&
          isHidden == other.isHidden &&
          metadata == other.metadata;
}
